name: keys
description: "Example of using keys."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  uuid: 4.3.3

dev_dependencies:
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
